export const GET_ALL_PROBLEMS = "GET_ALL_PROBLEMS";

export const SET_ALL_PROBLEMS_DATA = "SET_ALL_PROBLEMS_DATA";
export const IS_ALL_PROBLEM_LOADED_SUCCESSFULLY =
  "IS_ALL_PROBLEM_LOADED_SUCCESSFULLY";
export const SET_PROBLEMS_ERROR = "SET_PROBLEMS_ERROR";

export const LOAD_SINGLE_PROBLEM_INPROGRESS = "LOAD_SINGLE_PROBLEM_INPROGRESS";
export const LOAD_SINGLE_PROBLEM_SUCCESS = "LOAD_SINGLE_PROBLEM_SUCCESS";

export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER";
export const SIGNUP_PROGRESS = "SIGNUP_PROGRESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
