export const GET_ALL_PROBLEMS = "GET_ALL_PROBLEMS";
export const SET_ALL_PROBLEMS_DATA = "SET_ALL_PROBLEMS_DATA";

export const GET_FILTER = "GET_FILTER";
export const APPLY_FILTER = "APPLY_FILTER";

export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
